image: maven:3.9-eclipse-temurin-21

stages:
  - build
  - test
  - package
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - frontend/node_modules/

# Backend jobs
backend-build:
  stage: build
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS compile

backend-test:
  stage: test
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean test
  artifacts:
    paths:
      - backend/target/surefire-reports/
    reports:
      junit: backend/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/target/jacoco/coverage-reports/jacoco.xml

backend-package:
  stage: package
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - backend/target/*.jar

# Frontend jobs
frontend-build:
  stage: build
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm run build

frontend-test:
  stage: test
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm run test:unit

# Deploy jobs
generatepdf:
  image: ubuntu:20.04
  stage: deploy
  when: manual
  script:
    - apt-get update --allow-insecure-repositories
    - apt-get install -y wget
    - apt-get install -y fontconfig libfreetype6 libjpeg-turbo8 libpng16-16 libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi xfonts-base
    - wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
    - dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
    - apt-get -y install nodejs
    - apt-get -y install npm
    - npm install -g github-wikito-converter
    - apt-get -y install git
    - export my_url="${CI_PROJECT_URL:8}"
    - export final_url="https://gitlab-ci-token:$CI_JOB_TOKEN@$my_url"
    - git clone "$final_url.wiki.git"
    - gwtc $CI_PROJECT_NAME.wiki
    - wkhtmltopdf documentation.html wiki.pdf
  artifacts:
    paths:
      - wiki.pdf
  only:
    - web

pages:
  stage: deploy
  when: manual
  script:
    - cd backend
    - mvn clean package
    - mvn javadoc:javadoc
    - ls target/site/
    - ls target/site/apidocs/
    - mkdir -p ../.public/apidocs
    - cp -rf target/site/apidocs/* ../.public/apidocs/
    - cp -rf target/jacoco/* ../.public
    - cd ..
    - cp -rf page/index.html .public
    - mv -f .public public
  artifacts:
    paths:
      - public