spring.application.name=marketplace
spring.profiles.active=submission

# The key should be at least 256 bits long (32 bytes)
jwt.secret = super-duper-secure-and-long-secret-key-should-be-at-least-256-bit

# The expiration time in milliseconds (1 day = 86400000 ms)
jwt.expiration = 86400000
