package no.ntnu.idatt2105.marketplace.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Entity class representing a bookmark made by a user for a specific item.
 * This class is mapped to the "bookmarks" table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "bookmarks")
public class Bookmark {

  /**
   * Unique identifier for the bookmark.
   * This field is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The user who bookmarked the item.
   * This field is a foreign key reference to the {@link User} entity.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false)
  private User user;

  /**
   * The item that was bookmarked.
   * This field is a foreign key reference to the {@link Item} entity.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "item_id", nullable = false)
  private Item item;

  /**
   * The timestamp when the bookmark was created.
   * This field is automatically set to the current date and time when the bookmark is created.
   */
  @Column(nullable = false, updatable = false)
  private LocalDateTime bookmarkedAt = LocalDateTime.now();

  /**
   * Constructor to create a new bookmark with the specified user and item.
   *
   * @param user the user who bookmarked the item
   * @param item the item that was bookmarked
   */
  public Bookmark(User user, Item item) {
    this.user = user;
    this.item = item;
  }
}
