package no.ntnu.idatt2105.marketplace.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a Category in the marketplace.
 * This class is mapped to the "categories" table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "categories")
public class Category {

  /**
   * Unique identifier for the Category.
   * This value is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * Name of the Category.
   * This value must be unique and cannot be null.
   */
  @Column(nullable = false, unique = true, length = 100)
  private String name;
}
