package no.ntnu.idatt2105.marketplace.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing an ItemImage in the marketplace.
 * This class is mapped to the "item_images" table in the database.
 */
@Schema(description = "Represents an image attached to an item listing.")
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "item_images")
public class ItemImage {

  /**
   * Unique identifier for the ItemImage.
   * This field is automatically generated by the database.
   */
  @Schema(description = "Unique identifier for the image.", example = "1")
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The image data stored as a byte array (BLOB).
   * This field cannot be null.
   */
  @Schema(description = "Binary data of the image.")
  @Lob
  @Column(nullable = false, columnDefinition = "LONGBLOB")
  private byte[] data;

  /**
   * Original file name of the uploaded image.
   */
  @Schema(description = "Original file name of the image.", example = "image.jpg")
  @Column(name = "file_name")
  private String fileName;

  /**
   * MIME content type of the uploaded image.
   */
  @Schema(description = "MIME content type of the image.", example = "image/jpeg")
  @Column(name = "content_type")
  private String contentType;

  /**
   * Many-to-one relationship with the Item entity.
   * Each item can have multiple images.
   */
  @Schema(description = "The item associated with this image.")
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "item_id", nullable = false)
  private Item item;
}
