package no.ntnu.idatt2105.marketplace.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing an ItemImage in the marketplace.
 * This class is mapped to the "item_images" table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "item_images")
public class ItemImage {

  /**
   * Unique identifier for the ItemImage.
   * This field is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The image data stored as a byte array (BLOB).
   * This field cannot be null.
   */
  @Lob
  @Column(nullable = false, columnDefinition = "LONGBLOB")
  private byte[] data;

  /**
   * Original file name of the uploaded image.
   */
  @Column(name = "file_name")
  private String fileName;

  /**
   * MIME content type of the uploaded image.
   */
  @Column(name = "content_type")
  private String contentType;

  /**
   * Many-to-one relationship with the Item entity.
   * Each item can have multiple images.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "item_id", nullable = false)
  private Item item;
}
