package no.ntnu.idatt2105.marketplace.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Entity class representing an Item in the marketplace.
 * This class is mapped to the "listings" table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "listings")
public class Item {

  /**
   * Unique identifier for the Item.
   * This field is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * Title of the Item.
   * This field cannot be null and has a maximum length of 255 characters.
   */
  @Column(nullable = false, length = 255)
  private String title;

  /**
   * Description of the Item.
   * This field cannot be null and is stored as a TEXT field in the database.
   */
  @Column(nullable = false, columnDefinition = "TEXT")
  private String description;

  /**
   * Price of the Item.
   * This field cannot be null and must be a positive number.
   */
  @Column(nullable = false)
  private Double price; // TODO validate that this is a positive number?

  /**
   * Latitude of the Item's location.
   * This field is optional.
   */
  private Double locationLatitude;

  /**
   * Longitude of the Item's location.
   * This field is optional.
   */
  private Double locationLongitude;

  /**
   * The current status of the Item. (e.g., ACTIVE, SOLD, etc.)
   * This field defaults to {@code ItemStatus.ACTIVE}.
   */
  @Enumerated(EnumType.STRING)
  private ItemStatus status = ItemStatus.ACTIVE;

  /**
   * The category to which the Item belongs.
   * This field is a foreign key reference to the {@link Category} entity.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "category_id")
  private Category category;

  /**
   * The user who is selling the Item.
   * <p>
   * This field is a foreign key reference to the {@link User} entity and is used
   * internally for database mapping.
   * It is marked as {@code @JsonIgnore}, so it is not included in the JSON
   * representation of the Item.
   * Instead, only the seller's ID is exposed in the JSON via the
   * {@link #getSellerId()} method.
   */

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "seller_id")
  @JsonIgnore // Prevent full User Object from being serialized
  private User seller;

  /**
   * Gets the ID of the seller.
   * <p>
   * This value is included in the JSON serialization of the Item object under the
   * property {@code sellerId}.
   *
   * @return the ID of the seller, or {@code null} if no seller is set.
   */
  @JsonProperty("sellerId")
  public Long getSellerId() {
    return seller != null ? seller.getId() : null;
  }

  /**
   * The timestamp when the Item was created.
   * This field is automatically set to the current date and time when the Item is
   * created.
   * This field can not be null and is not updatable after creation.
   */
  @Column(nullable = false, updatable = false)
  private LocalDateTime createdAt = LocalDateTime.now();
}
