package no.ntnu.idatt2105.marketplace.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Entity class representing a reservation made by a user for a specific item.
 * This class is mapped to the "reservations" table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "reservations")
public class Reservation {

  /**
   * Unique identifier for the reservation.
   * This field is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The user who reserved the item.
   * This field is a foreign key reference to the {@link User} entity.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false)
  private User user;

  /**
   * The item that was reserved.
   * This field is a foreign key reference to the {@link Item} entity.
   * It is unique so that each item can only be reserved once at a time.
   */
  @OneToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "item_id", nullable = false, unique = true)
  private Item item;

  /**
   * The timestamp when the reservation was made.
   * This field is automatically set to the current date and time when the reservation is created.
   */
  @Column(nullable = false, updatable = false)
  private LocalDateTime reservedAt = LocalDateTime.now();

  /**
   * Constructor to create a new reservation with the specified user and item.
   *
   * @param user the user who reserved the item
   * @param item the item that was reserved
   */
  public Reservation(User user, Item item) {
    this.user = user;
    this.item = item;
  }
}
