package no.ntnu.idatt2105.marketplace.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

/**
 * Entity class representing a User in the marketplace.
 * This class is mapped to the "users" table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "users")
public class User {

  /**
   * Unique identifier for the User.
   * This field is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * Username of the User.
   * This field cannot be null, must be unique, and has a maximum length of 50
   * characters.
   */
  @Column(nullable = false, unique = true, length = 50)
  private String username;

  /**
   * Email address of the User.
   * This field cannot be null, must be unique, and has a maximum length of 100
   * characters.
   */
  @Column(nullable = false, unique = true, length = 100)
  private String email;

  /**
   * Password of the User.
   * This field cannot be null and has a maximum length of x characters.
   */
  @Column(nullable = false)
  private String password; // TODO: define max length, should be hashed?

  /**
   * Role of the User.
   * This field cannot be null and is stored as a string in the database.
   */
  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private Role role;

  /**
   * The timestamp when the User was created.
   * This field is automatically set to the current date and time when the User is
   * created.
   * This field cannot be null and is not updatable.
   */
  @Column(nullable = false, updatable = false)
  private LocalDateTime createdAt = LocalDateTime.now();
}