package no.ntnu.idatt2105.marketplace.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a User's profile image.
 * This class is mapped to the "user_images" table in the database.
 */
@Schema(description = "UserImage entity representing a user's profile image.")
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "user_images")
public class UserImage {

  /**
   * Unique identifier for the UserImage.
   * This field is automatically generated by the database.
   */
  @Schema(description = "Unique identifier for the user image.", example = "1")
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The image data stored as a byte array (BLOB).
   * This field cannot be null.
   */
  @Schema(description = "Image data of the user image.")
  @Lob
  @Column(nullable = false, columnDefinition = "LONGBLOB")
  private byte[] data;

  /**
   * Original file name of the uploaded image.
   */
  @Schema(description = "Original file name of the uploaded image.", example = "profile.jpg")
  @Column(name = "file_name")
  private String fileName;

  /**
   * MIME content type of the uploaded image.
   */
  @Schema(description = "MIME content type of the uploaded image.", example = "image/jpeg")
  @Column(name = "content_type")
  private String contentType;

  /**
   * One-to-one relationship with the User entity.
   * Each user can have only one profile image.
   */
  @Schema(description = "User associated with this image.")
  @OneToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false, unique = true)
  private User user;
}
