package no.ntnu.idatt2105.marketplace.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a User's profile image.
 * This class is mapped to the "user_images" table in the database.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "user_images")
public class UserImage {

  /**
   * Unique identifier for the UserImage.
   * This field is automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The image data stored as a byte array (BLOB).
   * This field cannot be null.
   */
  @Lob
  @Column(nullable = false, columnDefinition = "LONGBLOB")
  private byte[] data;

  /**
   * Original file name of the uploaded image.
   */
  @Column(name = "file_name")
  private String fileName;

  /**
   * MIME content type of the uploaded image.
   */
  @Column(name = "content_type")
  private String contentType;

  /**
   * One-to-one relationship with the User entity.
   * Each user can have only one profile image.
   */
  @OneToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false, unique = true)
  private User user;
}
