package no.ntnu.idatt2105.marketplace.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Entity class representing a User in the marketplace.
 * This class is mapped to the "users" table in the database.
 */
@Schema(description = "User entity representing a user in the marketplace.")
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "users")
public class User {

  /**
   * Unique identifier for the User.
   * This field is automatically generated by the database.
   */
  @Schema(description = "Unique identifier for the user.", example = "1")
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * Username of the User.
   * This field cannot be null, must be unique, and has a maximum length of 50
   * characters.
   */
  @Schema(description = "Username of the user.", example = "jonny_doe")
  @Column(nullable = false, unique = true, length = 50)
  private String username;

  /**
   * Email address of the User.
   * This field cannot be null, must be unique, and has a maximum length of 100
   * characters.
   */
  @Schema(description = "Email address of the user.")
  @Column(nullable = false, unique = true, length = 100)
  private String email;

  /**
   * First name of the User.
   * This field cannot be null and has a maximum length of 50 characters.
   */
  @Schema(description = "First name of the user.", example = "Jonny")
  @Column(nullable = false, length = 50)
  private String firstName;

  /**
   * Last name of the User.
   * This field cannot be null and has a maximum length of 50 characters.
   */
  @Schema(description = "Last name of the user.", example = "Doe")
  @Column(nullable = false, length = 50)
  private String lastName;

  /**
   * Password of the User.
   * This field cannot be null.
   */
  @Schema(description = "Password of the user.", example = "notgoodpassword123")
  @Column(nullable = false)
  private String password;

  /**
   * Role of the User.
   * This field cannot be null and is stored as a string in the database.
   */
  @Schema(description = "Role of the user.", example = "USER")
  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private Role role;

  /**
   * The timestamp when the User was created.
   * This field is automatically set to the current date and time when the User is
   * created.
   * This field cannot be null and is not updatable.
   */
  @Schema(description = "Timestamp when the user was created.")
  @Column(nullable = false, updatable = false)
  private LocalDateTime createdAt = LocalDateTime.now();
}